name: na_map_tools
description: a tool for working with location and map data (special features for IRAN)
version: 0.0.4
homepage: https://github.com/namini40/na_map_tools

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.na_map_tools
        pluginClass: NaMapToolsPlugin
      ios:
        pluginClass: NaMapToolsPlugin
      linux:
        pluginClass: NaMapToolsPlugin
      macos:
        pluginClass: NaMapToolsPlugin
      windows:
        pluginClass: NaMapToolsPlugin
      web:
        pluginClass: NaMapToolsWeb
        fileName: na_map_tools_web.dart

